# Generated by Django 5.1.15 on 2026-06-24 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("strategies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backtest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("strategy_snapshot", models.JSONField()),
                ("symbol", models.CharField(max_length=50)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, default=100000, max_digits=20),
                ),
                ("fees_bps", models.FloatField(default=5.0)),
                ("slippage_bps", models.FloatField(default=5.0)),
                ("oos_split_date", models.DateField(blank=True, null=True)),
                ("periods_per_year", models.IntegerField(default=252)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("result_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtests",
                        to="strategies.strategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
                ("equity_curve", models.JSONField(default=list)),
                ("tearsheet_path", models.CharField(blank=True, max_length=500)),
                ("data_snapshot_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backtest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="backtests.backtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                (
                    "side",
                    models.CharField(choices=[("long", "Long")], default="long", max_length=5),
                ),
                ("qty", models.FloatField()),
                ("entry_ts", models.DateTimeField(blank=True, null=True)),
                ("entry_px", models.FloatField(blank=True, null=True)),
                ("exit_ts", models.DateTimeField(blank=True, null=True)),
                ("exit_px", models.FloatField(blank=True, null=True)),
                ("fees", models.FloatField(default=0.0)),
                ("pnl", models.FloatField(blank=True, null=True)),
                (
                    "backtest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="backtests.backtest",
                    ),
                ),
            ],
            options={
                "ordering": ["entry_ts", "id"],
            },
        ),
    ]
